### ISSUE TITLE
Examples on usage

### ISSUE THREAD

**Issue by nunokaeru** [allyourcodebase/catch2#1]
I've been trying to use Catch2 in my C++ repo using the Zig build system but am having trouble with figuring out how to import / use.

For example a simple test case with

```c++
#define CATCH_CONFIG_MAIN // This tells Catch to provide a main() - only do this in one cpp file

#include <catch2/catch_test_macros.hpp>

TEST_CASE("Basic")
{ 
    REQUIRE(true)
}
```

I get the error `test\tests.cpp:3:10: error: 'catch2/catch_test_macros.hpp' file not found #include <catch2/catch_test_macros.hpp>`

This is my build configuration
```zig
    // Unit testing
    const catch2_dep = b.dependency("catch2", .{
        .target = target,
        .optimize = optimize,
    });
    const catch2 = catch2_dep.artifact("Catch2WithMain");

    const unit = b.addExecutable(.{
        .name = "test",
        .target = target,
        .optimize = optimize,
    });
    unit.linkLibCpp();
    unit.addCSourceFile(.{
        .file = .{ .cwd_relative = "test/tests.cpp" },
        .flags = &cppFlags,
    });
    unit.linkLibrary(lib);
    unit.linkLibrary(catch2);
    b.installArtifact(unit);
    const run_unit = b.addRunArtifact(unit);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_unit.step);
```

Would be lovely to add an example on the README or even a "test" in this repo itself with the smallest of examples

**Comment by agagniere** [comment]
Good call:
- In the readme I didn't mention that one had to link to both `Catch2` and `Catch2WithMain` libraries (just like when compiling manually, with `-l Catch2 -l Catch2WithMain`)
- I named one artifact `catch2` instead of `Catch2`

And indeed the tests built in the top-level `build.zig` are not straightforward to reuse.
